#spring:
#  application:
#    name: batch-sample
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  batch:
#    jdbc:
#      initialize-schema: always

#spring:
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#      username: postgres
#      password: postgres
#      driver-class-name: org.postgresql.Driver
#      jdbc-url: jdbc:postgresql://localhost:5432/batch
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      name: NEXT_STEP_TASK
#mybatis:
#  mapper-locations: classpath:mapper/*.xml


server:
  port: 8080
  shutdown: graceful

spring:
  main:
    web-application-type: servlet